version: "3.3"
services:
  demo:
    image: bluesmonk/poetry-demo:latest
    env_file:
      - .env
    build:
      context: ./src
      dockerfile: Dockerfile
    networks:
      - demo-network
    volumes:
    #   # Update this to wherever you want VS Code to mount the folder of your project
      - ./src/mypackage:/src/mypackage
      - ./src/pyproject.toml:/src/pyproject.toml
      - ./src/poetry.toml:/src/poetry.toml
      - ./src/poetry.lock:/src/poetry.lock

networks:
  demo-network:
    driver: bridge
